### ISSUE TITLE
already is one

### ISSUE THREAD

**Issue by joeblew99** [cadaniel/flutter_pdf_printer#1]
Do you know about https://github.com/DavBfr/dart_pdf ?

**Comment by cadaniel** [comment]
So that package requires you to use their pdf library. This one takes a file from the file system and prints it from there.

**Comment by joeblew99** [comment]
they also use webvew. I guess for the print preview ?https://github.com/DavBfr/dart_pdf/blob/master/printing/ios/Classes/SwiftPrintingPlugin.swift#L148

**Comment by cadaniel** [comment]
The print preview is still done. It's actually rendered in native code.
