### ISSUE TITLE
Kotlin error - The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher

### ISSUE THREAD

**Issue by hussain-badusha** [cadaniel/flutter_pdf_printer#2]
Hi,
I've been developing a flutter app to automate printing process as much as possible.
So, i want to print a downloaded pdf from internet. i searched and looked at the printing package and it doesn't not allow me to load existing pdf and print it. 
So i searched more and i got flutter_pdf_printer and it is exactly what i was looking for.
But unfortunately, plugin is not working saying kotlin error.
Fyi, i'm attaching a screenshot
![flutter-print-kotlin-error](https://user-images.githubusercontent.com/56146898/74305926-267ef680-4d87-11ea-8f3f-6ea963054230.PNG)

Thanks,
Hussain

**Comment by cadaniel** [comment]
So flutter PDF printer requires the min kotlin version to 1.3.10, it appears your project is using 1.2.71. I'd recommend going into your build.gradle and upgrading to the latest version of kotlin.

**Comment by hussain-badusha** [comment]
Hi Daniel,
Thanks for reply

Sorry for the late reply. I already managed to print it successfully. 
Now i want to know one more thing. Please clarify if it is possible or not.
What i want to do is that i need to print files without user intervention (without preview)
Is that doable with **flutter** or with your plugin **flutter_pdf_printer** with additional changes to it?

Thanks,
Hussain

**Comment by cadaniel** [comment]
AFAIK it's not possible. This is using platform channels to print, which shows the native views. 

Closing the issue.

**Comment by manoj5047** [comment]
> Hi Daniel,
> Thanks for reply
> 
> Sorry for the late reply. I already managed to print it successfully.
> Now i want to know one more thing. Please clarify if it is possible or not.
> What i want to do is that i need to print files without user intervention (without preview)
> Is that doable with **flutter** or with your plugin **flutter_pdf_printer** with additional changes to it?
> 
> Thanks,
> Hussain

Hi, I am facing same issue. Can u please tell what  have done to get it work.
